-- FP-43784 lookup — bucket: Xbox + UWP (237 unique nicks, case-insensitive)
-- Read-only. NOLOCK on every Prod table.
-- Match key: Users.Username (SQL_Latin1_General_CP1_CI_AS).
-- Payer rule mirrors SqlMonetizationProvider.GetHasPaidTransactions().

;WITH PollNicks(Nickname) AS (
    SELECT v.Nickname COLLATE SQL_Latin1_General_CP1_CI_AS
    FROM (VALUES
    (N'Kazi77'),
    (N'Durt Baghe'),
    (N'kikotheWplayer'),
    (N'ElfyFrost'),
    (N'Ryguy4104'),
    (N'Captaineuro3989'),
    (N'bwojo122'),
    (N'Danrance12'),
    (N'Punisher2274'),
    (N'Updated Version'),
    (N'Basketball2k864'),
    (N'Midnightoker940'),
    (N'AttyX666'),
    (N'BeastMaster6673'),
    (N'KarolKARP'),
    (N'Patrick53079'),
    (N'gregorian_andy'),
    (N'DriftMonkey5750'),
    (N'Badger3297'),
    (N'Silverwolf#1887'),
    (N'minimooi'),
    (N'SteepledPizza84'),
    (N'Redraven68'),
    (N'XchubqcX'),
    (N'KUBOWSKI GOL'),
    (N'Superwarrior627'),
    (N'Twiggytristen'),
    (N'Scoobydoo5291'),
    (N'DSX DREAMZ'),
    (N'Mightyargyle165'),
    (N'Courtney benning'),
    (N'Alkazar719'),
    (N'DarkPass77'),
    (N'Xx XAgainX xX'),
    (N'Wantedtheme3372'),
    (N'Kevyn62'),
    (N'xXoMERLINoXx'),
    (N'PhoenixFire'),
    (N'PooToe27'),
    (N'highgamer3421'),
    (N'MrDB78'),
    (N'Darth Imperatus'),
    (N'Dark88c7'),
    (N'MR BARD1944'),
    (N'Williams'),
    (N'RexCarver'),
    (N'ballinxaz'),
    (N'Lucapicc'),
    (N'Trout2king'),
    (N'YIYO824C'),
    (N'LIBRAx1517'),
    (N'Stealth'),
    (N'TPBCrazyCar'),
    (N'Badassredck'),
    (N'NickGreken'),
    (N'Delboy7676'),
    (N'Jack1314'),
    (N'LegendaryFishing'),
    (N'AlienDoge698407'),
    (N'PTSDSOLDIER77'),
    (N'BowlerGaming948'),
    (N'IDONTWIN1924'),
    (N'Mendedmanatee07'),
    (N'Diegosouza99950'),
    (N'pedrofp38'),
    (N'smiler1954'),
    (N'Lethal sons'),
    (N'Jwooly22'),
    (N'Sharkhunter222'),
    (N'BatteMrBrams'),
    (N'GALAXYXFORCE722'),
    (N'MZ1909'),
    (N'Fumbles80'),
    (N'DuMbDoNuT'),
    (N'EBH PHOENIXA'),
    (N'TEUZIN k9'),
    (N'SpirantParrot45'),
    (N'DavecusPrime'),
    (N'Liam051198'),
    (N'BuggCityEnt'),
    (N'Lil Cousin'),
    (N'MysticalClaw516'),
    (N'DeaserMK2'),
    (N'Dony2662'),
    (N'Ala Montana'),
    (N'Skallagoo'),
    (N'JUANSHOULDINER'),
    (N'Tha dooo4521'),
    (N'Pops1823'),
    (N'RowdyWs671017'),
    (N'KGE SNEAKY ME'),
    (N'GhostSlayer8648'),
    (N'TTVxBdawgKz'),
    (N'HappyHoodz'),
    (N'CezarXX8471'),
    (N'BEYOND xxHELP'),
    (N'Gonzo1964'),
    (N'Lilstumpy328 aka Ayden'),
    (N'THEmajicCARPET'),
    (N'muzioreq'),
    (N'F4Zion Weezy'),
    (N'FisherMan1120'),
    (N'acon099786'),
    (N'Twiztidgurl96'),
    (N'Prstonrobinson'),
    (N'AshleyLynn86574'),
    (N'SeattleColt'),
    (N'deathbybellyrub'),
    (N'Catfish7305'),
    (N'Leotect'),
    (N'Fishingbro1861'),
    (N'Hi'),
    (N'NoahDestroyer18. (xbox gamertag)'),
    (N'W9USA'),
    (N'tig3rjam56'),
    (N'andylemming'),
    (N'MoldenXDemon'),
    (N'lordminecraftxc'),
    (N'kunamutaorez'),
    (N'sm3ll1nch33se'),
    (N'Dbomb Deadly'),
    (N'junkymonkey258'),
    (N'hollisbot'),
    (N'Zaypro64'),
    (N'mikroparasyte'),
    (N'Jatmae'),
    (N'Iurito7282'),
    (N'my account is not level 10 or higher'),
    (N'WarEagle312'),
    (N'Mightynarwhal6'),
    (N'PurrBurger'),
    (N'Jynxkies'),
    (N'Yakn4Bass7'),
    (N'Frankie20213855'),
    (N'Sacredsoul68'),
    (N'U4GChaser'),
    (N'DocDanger776233'),
    (N'Blueorchid7495'),
    (N'X 12gaJohn X'),
    (N'nggaaah'),
    (N'Fluro78'),
    (N'SOILFLIGHT'),
    (N'tesco4524'),
    (N'Vo'),
    (N'Face apad12'),
    (N'Mortalstomper'),
    (N'Mikus#1994'),
    (N'Bradmanjr'),
    (N'TRgame77'),
    (N'Opsblitz2330'),
    (N'Brazenleader#641'),
    (N'Haplo8098'),
    (N'Solar384'),
    (N'SNOWKERAONE'),
    (N'ZeroRitualTheFisher'),
    (N'Aesiour'),
    (N'Daumier6080'),
    (N'Saturated 56'),
    (N'xLxcky'),
    (N'MUERE RATA1993'),
    (N'ELTITOGRAVY6'),
    (N'BIG AL GREG'),
    (N'Cartucho67'),
    (N'DANKVKUSH420'),
    (N'YoDarkkTKTOK'),
    (N'TheDroGod'),
    (N'Tinelen'),
    (N'Ash'),
    (N'Zack'),
    (N'RingedEel223513'),
    (N'Itsshan420'),
    (N'N111k0n'),
    (N'Anton51970'),
    (N'Communiqe'),
    (N'Sebago9414'),
    (N'WisniakG'),
    (N'SzymonNa01'),
    (N'akirosan07'),
    (N'kiwiis#9694'),
    (N'AzureAir2184164'),
    (N'brycevotto1414'),
    (N'Rutt2010'),
    (N'Hugo TZH'),
    (N'RRMC SASSY B'),
    (N'Keeshot'),
    (N'TKGM4642'),
    (N'Chapattack8135'),
    (N'iissmmaa195535'),
    (N'aronnTTv'),
    (N'Flystergrilo29'),
    (N'PekRomArt'),
    (N'PROJASSY5980'),
    (N'Elpachino99'),
    (N'lsauls'),
    (N'Renzo4069'),
    (N'Zubugames'),
    (N'DentalMango4'),
    (N'H3ADHUNT3R2222'),
    (N'diogo'),
    (N'MidwayLeader409'),
    (N'SoughtBody669'),
    (N'benaa95'),
    (N'Taz( tasmanian devil )'),
    (N'DziudoRok'),
    (N'Valetp'),
    (N'Bionoc Bark'),
    (N'Flourylmp'),
    (N'TRhodes99'),
    (N'Parchedgecko'),
    (N'Potatodog212538'),
    (N'Rancherrobb'),
    (N'Sunshine0369564'),
    (N'Dinonuggies1215'),
    (N'rubio88'),
    (N'Mustang25#701'),
    (N'GTz Turboturtle'),
    (N'TheShadows#4966'),
    (N'Benceft66'),
    (N'Mini Mike328'),
    (N'RogueTiger13151'),
    (N'ATFk1llsDogs'),
    (N'M00N1IGHT420'),
    (N'Toretto8674'),
    (N'NatalyRedFox'),
    (N'Not Swevy w'),
    (N'K1NG2981'),
    (N'Diablogalaxi487'),
    (N'Coucoupolo4862'),
    (N'Etorrsc'),
    (N'Pop'),
    (N'Raidedbyoff'),
    (N'Trapper101047'),
    (N'Inumakis4474'),
    (N'Enemybaker95664'),
    (N'Marke46'),
    (N'Katanzy'),
    (N'Burnvictim666')
    ) AS v(Nickname)
),
MatchedUsers AS (
    SELECT p.Nickname AS PolledNickname, u.UserId, u.Username AS DbUsername
    FROM PollNicks p
    INNER JOIN dbo.Users u WITH (NOLOCK) ON u.Username = p.Nickname
),
PaidUsers AS (
    SELECT DISTINCT t.UserId
    FROM dbo.Transactions t WITH (NOLOCK)
    INNER JOIN MatchedUsers m ON m.UserId = t.UserId
    WHERE t.Status = 'Complete'
      AND t.PaymentSystemId <> 'WebAdmin'
      AND t.Price <> 0
)
SELECT p.Nickname        AS PolledNickname,
       mu.DbUsername     AS MatchedUsername,
       pr.Level          AS Level,
       uc.Country        AS Country,
       CASE WHEN pu.UserId IS NOT NULL THEN 1 ELSE 0 END AS IsPayer
FROM PollNicks p
LEFT JOIN MatchedUsers mu ON mu.PolledNickname = p.Nickname
LEFT JOIN dbo.Profiles pr WITH (NOLOCK) ON pr.UserId = mu.UserId
LEFT JOIN dbo.UserCountries uc WITH (NOLOCK) ON uc.UserId = mu.UserId
LEFT JOIN PaidUsers pu ON pu.UserId = mu.UserId
ORDER BY p.Nickname;
