"""Fight-profile comparison for the FP-46092 player: before vs after the first Denuvo detection.

Inputs (same folder): fishfact-hooked.csv, fishingsessionscatch.csv, fishinglog-fights.tsv.
Outputs: fight-metrics.md (summary tables) and, when matplotlib is available, fight-charts.png.
Run: python analyze_fights.py
"""
import csv
import io
import os
import statistics as st
from datetime import datetime, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
SPLIT = datetime(2026, 9, 3, 0, 0, 0)  # first Denuvo detection day (UTC)


def read_csv(name, delimiter=","):
    with io.open(os.path.join(HERE, name), encoding="utf-8") as f:
        return list(csv.DictReader(f, delimiter=delimiter))


def fnum(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def pdt(v):
    v = v.strip()
    for fmt in ("%Y-%m-%d %H:%M:%S.%f", "%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S.%fZ", "%Y-%m-%dT%H:%M:%SZ"):
        try:
            return datetime.strptime(v, fmt)
        except ValueError:
            pass
    return None


def q(vals, p):
    vals = sorted(v for v in vals if v is not None)
    if not vals:
        return None
    k = (len(vals) - 1) * p
    lo, hi = int(k), min(int(k) + 1, len(vals) - 1)
    return vals[lo] + (vals[hi] - vals[lo]) * (k - lo)


def fmt(v, d=1):
    return "-" if v is None else ("%.*f" % (d, v))


# --- FishFact: caught fish only -------------------------------------------------------------
ff = []
for r in read_csv("fishfact-hooked.csv"):
    if not r["CaughtAt"]:
        continue
    w, sec, dist = fnum(r["Weight"]), fnum(r["FightSec"]), fnum(r["HookedDistance"])
    hooked = pdt(r["HookedAt"])
    if hooked is None and r["CaughtAt"] and sec:
        hooked = pdt(r["CaughtAt"]) - timedelta(seconds=sec)  # hooked update never landed (NaN distance)
    if hooked is None or w is None or sec is None or sec <= 0:
        continue
    ff.append({
        "t": hooked, "day": hooked.strftime("%Y-%m-%d"), "w": w, "sec": sec, "dist": dist,
        "spk": sec / w if w > 0 else None,           # seconds per kg
        "reel": (dist / sec) if dist else None,      # implied reel speed, m/s
        "exp": fnum(r["Exp"]), "after": hooked >= SPLIT,
    })

# --- FishingSessionsCatch: force vs tackle load ------------------------------------------------
fsc = []
for r in read_csv("fishingsessionscatch.csv"):
    t = pdt(r["CycleStart"])
    force, load, sec = fnum(r["FishForce"]), fnum(r["MinMaxLoad"]), fnum(r["FightSec"])
    if t is None or force is None or load is None or sec is None or sec <= 0:
        continue
    fsc.append({"t": t, "ratio": force / load if load > 0 else None, "sec": sec, "after": t >= SPLIT})

# --- fishingLog fights: stamina at catch ----------------------------------------------------------
fl = []
for r in read_csv("fishinglog-fights.tsv", delimiter="\t"):
    if r["end"] != "caught":
        continue
    t = pdt(r["t0"])
    stam, sec, w = fnum(r["stamina"]), fnum(r["sec"]), fnum(r["kg"])
    if t is None or stam is None or sec is None:
        continue
    fl.append({"t": t, "stamina": stam, "sec": sec, "w": w, "after": t >= SPLIT})


def period_rows(items, after):
    return [i for i in items if i["after"] == after]


out = []
out.append("# Fight metrics, user 88236613-788f-4fcc-a8b5-7b229b8ed1fc\n")
out.append("Split at 2026-09-03 00:00 UTC (first Denuvo detection day). Caught fish only. Generated by analyze_fights.py.\n")
out.append("## FishFact (Stats), all history in the pull\n")
out.append("| Period | caught | fight s median | fight s p90 | s/kg median | s/kg p10 | weight median | weight max | reel m/s median | reel m/s max | fights <10 s and >50 kg |")
out.append("|--------|--------|----------------|-------------|-------------|----------|---------------|------------|-----------------|--------------|-------------------------|")
for label, after in (("before", False), ("after", True)):
    rows = period_rows(ff, after)
    fast_big = sum(1 for r in rows if r["sec"] < 10 and r["w"] > 50)
    out.append("| %s | %d | %s | %s | %s | %s | %s | %s | %s | %s | %d |" % (
        label, len(rows), fmt(q([r["sec"] for r in rows], .5)), fmt(q([r["sec"] for r in rows], .9)),
        fmt(q([r["spk"] for r in rows], .5), 2), fmt(q([r["spk"] for r in rows], .1), 2),
        fmt(q([r["w"] for r in rows], .5)), fmt(max(r["w"] for r in rows) if rows else None),
        fmt(q([r["reel"] for r in rows], .5), 2), fmt(max((r["reel"] for r in rows if r["reel"]), default=None), 2), fast_big))

out.append("\nPer day:\n")
out.append("| Day | caught | fight s median | s/kg median | weight median | weight max | reel m/s median | reel m/s max | <10 s and >50 kg |")
out.append("|-----|--------|----------------|-------------|---------------|------------|-----------------|--------------|------------------|")
for day in sorted(set(r["day"] for r in ff)):
    rows = [r for r in ff if r["day"] == day]
    out.append("| %s | %d | %s | %s | %s | %s | %s | %s | %d |" % (
        day, len(rows), fmt(q([r["sec"] for r in rows], .5)), fmt(q([r["spk"] for r in rows], .5), 2),
        fmt(q([r["w"] for r in rows], .5)), fmt(max(r["w"] for r in rows)),
        fmt(q([r["reel"] for r in rows], .5), 2), fmt(max((r["reel"] for r in rows if r["reel"]), default=None), 2),
        sum(1 for r in rows if r["sec"] < 10 and r["w"] > 50)))

out.append("\n## FishingSessionsCatch: fish force / tackle min max load vs fight time\n")
out.append("| Period | catches | force/load median | force/load p90 | fight s median where force/load > 2 |")
out.append("|--------|---------|-------------------|----------------|--------------------------------------|")
for label, after in (("before", False), ("after", True)):
    rows = period_rows(fsc, after)
    strong = [r["sec"] for r in rows if r["ratio"] and r["ratio"] > 2]
    out.append("| %s | %d | %s | %s | %s |" % (label, len(rows), fmt(q([r["ratio"] for r in rows], .5), 2),
                                             fmt(q([r["ratio"] for r in rows], .9), 2), fmt(q(strong, .5))))

out.append("\n## fishingLog (14-day window): fish stamina at the moment of catch\n")
out.append("| Period | caught | stamina median | stamina p10 | share with stamina >= 0.99 | fight s median |")
out.append("|--------|--------|----------------|-------------|----------------------------|----------------|")
for label, after in (("before", False), ("after", True)):
    rows = period_rows(fl, after)
    share = (sum(1 for r in rows if r["stamina"] >= 0.99) / len(rows) * 100) if rows else None
    out.append("| %s | %d | %s | %s | %s%% | %s |" % (label, len(rows), fmt(q([r["stamina"] for r in rows], .5), 3),
                                                    fmt(q([r["stamina"] for r in rows], .1), 3), fmt(share, 0),
                                                    fmt(q([r["sec"] for r in rows], .5))))

with io.open(os.path.join(HERE, "fight-metrics.md"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("\n".join(out))

# --- charts -------------------------------------------------------------------------------------
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:
    print("matplotlib not available; charts skipped")
    raise SystemExit(0)

fig, axes = plt.subplots(1, 3, figsize=(18, 5.5))
for after, color, label in ((False, "#3e80cf", "before 2026-09-03"), (True, "#e0483e", "from 2026-09-03")):
    rows = period_rows(ff, after)
    axes[0].scatter([r["w"] for r in rows], [r["sec"] for r in rows], s=14, alpha=.7, c=color, label=label)
    rr = [r for r in rows if r["reel"]]
    axes[1].scatter([r["dist"] for r in rr], [r["sec"] for r in rr], s=14, alpha=.7, c=color, label=label)
    fr = period_rows(fl, after)
    axes[2].scatter([r["w"] for r in fr], [r["stamina"] for r in fr], s=14, alpha=.7, c=color, label=label)
axes[0].set_xscale("log"); axes[0].set_yscale("log")
axes[0].set_xlabel("fish weight, kg"); axes[0].set_ylabel("fight duration, s"); axes[0].set_title("FishFact: weight vs fight duration")
axes[1].set_xscale("log"); axes[1].set_yscale("log")
axes[1].set_xlabel("hooked distance, m"); axes[1].set_ylabel("fight duration, s"); axes[1].set_title("FishFact: distance vs fight duration")
axes[2].set_xscale("log")
axes[2].set_xlabel("fish weight, kg"); axes[2].set_ylabel("stamina at catch"); axes[2].set_title("fishingLog: stamina at catch (14 days)")
for ax in axes:
    ax.grid(True, which="both", alpha=.25); ax.legend(loc="best", fontsize=8)
fig.tight_layout()
fig.savefig(os.path.join(HERE, "fight-charts.png"), dpi=130)
print("chart saved: fight-charts.png")
